[package]
name = "raw-window-handle"
version = "0.5.2"
authors = ["Osspial <osspial@gmail.com>"]
edition = "2021"
description = "Interoperability library for Rust Windowing applications."
license = "MIT OR Apache-2.0 OR Zlib"
repository = "https://github.com/rust-windowing/raw-window-handle"
keywords = ["windowing"]
readme = "README.md"
documentation = "https://docs.rs/raw-window-handle"
rust-version = "1.64"

[features]
alloc = []
std = ["alloc"]

# Unstable feature to allow the use of `wasm-bindgen` in the `wasm` target.
# 
# This is radioactive semver-wise. Do not rely on this in stable code. Any code enabled by this
# feature can be changed or removed in a breaking way at any time. In fact, this feature could
# be removed entirely tomorrow.
# 
# The point being: rely on this at your own peril.
unstable_web_handles = ["wasm-bindgen", "std"]

[target.'cfg(target_family = "wasm")'.dependencies.wasm-bindgen]
version = "0.2.87"
default-features = false
features = ["std"]
optional = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
